/*
 * Ekşi Sözlük UnPublic API
 * Ekşi sözlük'ün public olmayan apiyı. Bunu kullanmanın size yasal yaptırımları olabilir. Bunu kullanan kişiler bu riski göze almış olarak düşünülür.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: umt.toker@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hasssektor.eksiapi.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * AutocomplateResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-11T23:04:25.106+03:00")
public class AutocomplateResponse {
  @SerializedName("Titles")
  private List<String> titles = new ArrayList<String>();

  @SerializedName("Query")
  private String query = null;

  @SerializedName("Nicks")
  private List<String> nicks = new ArrayList<String>();

  public AutocomplateResponse titles(List<String> titles) {
    this.titles = titles;
    return this;
  }

  public AutocomplateResponse addTitlesItem(String titlesItem) {
    this.titles.add(titlesItem);
    return this;
  }

   /**
   * Get titles
   * @return titles
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getTitles() {
    return titles;
  }

  public void setTitles(List<String> titles) {
    this.titles = titles;
  }

  public AutocomplateResponse query(String query) {
    this.query = query;
    return this;
  }

   /**
   * Get query
   * @return query
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getQuery() {
    return query;
  }

  public void setQuery(String query) {
    this.query = query;
  }

  public AutocomplateResponse nicks(List<String> nicks) {
    this.nicks = nicks;
    return this;
  }

  public AutocomplateResponse addNicksItem(String nicksItem) {
    this.nicks.add(nicksItem);
    return this;
  }

   /**
   * Get nicks
   * @return nicks
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getNicks() {
    return nicks;
  }

  public void setNicks(List<String> nicks) {
    this.nicks = nicks;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutocomplateResponse autocomplateResponse = (AutocomplateResponse) o;
    return Objects.equals(this.titles, autocomplateResponse.titles) &&
        Objects.equals(this.query, autocomplateResponse.query) &&
        Objects.equals(this.nicks, autocomplateResponse.nicks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(titles, query, nicks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutocomplateResponse {\n");
    
    sb.append("    titles: ").append(toIndentedString(titles)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    nicks: ").append(toIndentedString(nicks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

