/*
 * Ekşi Sözlük UnPublic API
 * Ekşi sözlük'ün public olmayan apiyı. Bunu kullanmanın size yasal yaptırımları olabilir. Bunu kullanan kişiler bu riski göze almış olarak düşünülür.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: umt.toker@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hasssektor.eksiapi.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * AutocomplateNickResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-11T23:04:25.106+03:00")
public class AutocomplateNickResponse {
  @SerializedName("Nicks")
  private List<String> nicks = new ArrayList<String>();

  public AutocomplateNickResponse nicks(List<String> nicks) {
    this.nicks = nicks;
    return this;
  }

  public AutocomplateNickResponse addNicksItem(String nicksItem) {
    this.nicks.add(nicksItem);
    return this;
  }

   /**
   * Get nicks
   * @return nicks
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getNicks() {
    return nicks;
  }

  public void setNicks(List<String> nicks) {
    this.nicks = nicks;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutocomplateNickResponse autocomplateNickResponse = (AutocomplateNickResponse) o;
    return Objects.equals(this.nicks, autocomplateNickResponse.nicks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nicks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutocomplateNickResponse {\n");
    
    sb.append("    nicks: ").append(toIndentedString(nicks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

