/*
 * Ekşi Sözlük UnPublic API
 * Ekşi sözlük'ün public olmayan apiyı. Bunu kullanmanın size yasal yaptırımları olabilir. Bunu kullanan kişiler bu riski göze almış olarak düşünülür.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: umt.toker@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hasssektor.eksiapi.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.hasssektor.eksiapi.models.Author;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * CaylakFavoritesResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-11T23:04:25.106+03:00")
public class CaylakFavoritesResponse {
  @SerializedName("EntryId")
  private Integer entryId = null;

  @SerializedName("Caylaks")
  private List<Author> caylaks = new ArrayList<Author>();

  public CaylakFavoritesResponse entryId(Integer entryId) {
    this.entryId = entryId;
    return this;
  }

   /**
   * Get entryId
   * @return entryId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getEntryId() {
    return entryId;
  }

  public void setEntryId(Integer entryId) {
    this.entryId = entryId;
  }

  public CaylakFavoritesResponse caylaks(List<Author> caylaks) {
    this.caylaks = caylaks;
    return this;
  }

  public CaylakFavoritesResponse addCaylaksItem(Author caylaksItem) {
    this.caylaks.add(caylaksItem);
    return this;
  }

   /**
   * Get caylaks
   * @return caylaks
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Author> getCaylaks() {
    return caylaks;
  }

  public void setCaylaks(List<Author> caylaks) {
    this.caylaks = caylaks;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CaylakFavoritesResponse caylakFavoritesResponse = (CaylakFavoritesResponse) o;
    return Objects.equals(this.entryId, caylakFavoritesResponse.entryId) &&
        Objects.equals(this.caylaks, caylakFavoritesResponse.caylaks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entryId, caylaks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CaylakFavoritesResponse {\n");
    
    sb.append("    entryId: ").append(toIndentedString(entryId)).append("\n");
    sb.append("    caylaks: ").append(toIndentedString(caylaks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

