/*
 * Ekşi Sözlük UnPublic API
 * Ekşi sözlük'ün public olmayan apiyı. Bunu kullanmanın size yasal yaptırımları olabilir. Bunu kullanan kişiler bu riski göze almış olarak düşünülür.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: umt.toker@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hasssektor.eksiapi.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * EntryCounts
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-11T23:04:25.106+03:00")
public class EntryCounts {
  @SerializedName("BeforeFirstEntry")
  private Integer beforeFirstEntry = null;

  @SerializedName("AfterLastEntry")
  private Integer afterLastEntry = null;

  @SerializedName("Buddy")
  private Integer buddy = null;

  @SerializedName("Total")
  private Integer total = null;

  public EntryCounts beforeFirstEntry(Integer beforeFirstEntry) {
    this.beforeFirstEntry = beforeFirstEntry;
    return this;
  }

   /**
   * Get beforeFirstEntry
   * @return beforeFirstEntry
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getBeforeFirstEntry() {
    return beforeFirstEntry;
  }

  public void setBeforeFirstEntry(Integer beforeFirstEntry) {
    this.beforeFirstEntry = beforeFirstEntry;
  }

  public EntryCounts afterLastEntry(Integer afterLastEntry) {
    this.afterLastEntry = afterLastEntry;
    return this;
  }

   /**
   * Get afterLastEntry
   * @return afterLastEntry
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getAfterLastEntry() {
    return afterLastEntry;
  }

  public void setAfterLastEntry(Integer afterLastEntry) {
    this.afterLastEntry = afterLastEntry;
  }

  public EntryCounts buddy(Integer buddy) {
    this.buddy = buddy;
    return this;
  }

   /**
   * Get buddy
   * @return buddy
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getBuddy() {
    return buddy;
  }

  public void setBuddy(Integer buddy) {
    this.buddy = buddy;
  }

  public EntryCounts total(Integer total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntryCounts entryCounts = (EntryCounts) o;
    return Objects.equals(this.beforeFirstEntry, entryCounts.beforeFirstEntry) &&
        Objects.equals(this.afterLastEntry, entryCounts.afterLastEntry) &&
        Objects.equals(this.buddy, entryCounts.buddy) &&
        Objects.equals(this.total, entryCounts.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(beforeFirstEntry, afterLastEntry, buddy, total);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntryCounts {\n");
    
    sb.append("    beforeFirstEntry: ").append(toIndentedString(beforeFirstEntry)).append("\n");
    sb.append("    afterLastEntry: ").append(toIndentedString(afterLastEntry)).append("\n");
    sb.append("    buddy: ").append(toIndentedString(buddy)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

