/*
 * Ekşi Sözlük UnPublic API
 * Ekşi sözlük'ün public olmayan apiyı. Bunu kullanmanın size yasal yaptırımları olabilir. Bunu kullanan kişiler bu riski göze almış olarak düşünülür.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: umt.toker@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hasssektor.eksiapi.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.hasssektor.eksiapi.models.Author;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * FavoritesResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-11T23:04:25.106+03:00")
public class FavoritesResponse {
  @SerializedName("EntryId")
  private Integer entryId = null;

  @SerializedName("Authors")
  private List<Author> authors = new ArrayList<Author>();

  @SerializedName("Buddies")
  private List<Author> buddies = new ArrayList<Author>();

  public FavoritesResponse entryId(Integer entryId) {
    this.entryId = entryId;
    return this;
  }

   /**
   * Get entryId
   * @return entryId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getEntryId() {
    return entryId;
  }

  public void setEntryId(Integer entryId) {
    this.entryId = entryId;
  }

  public FavoritesResponse authors(List<Author> authors) {
    this.authors = authors;
    return this;
  }

  public FavoritesResponse addAuthorsItem(Author authorsItem) {
    this.authors.add(authorsItem);
    return this;
  }

   /**
   * Get authors
   * @return authors
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Author> getAuthors() {
    return authors;
  }

  public void setAuthors(List<Author> authors) {
    this.authors = authors;
  }

  public FavoritesResponse buddies(List<Author> buddies) {
    this.buddies = buddies;
    return this;
  }

  public FavoritesResponse addBuddiesItem(Author buddiesItem) {
    this.buddies.add(buddiesItem);
    return this;
  }

   /**
   * Get buddies
   * @return buddies
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Author> getBuddies() {
    return buddies;
  }

  public void setBuddies(List<Author> buddies) {
    this.buddies = buddies;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FavoritesResponse favoritesResponse = (FavoritesResponse) o;
    return Objects.equals(this.entryId, favoritesResponse.entryId) &&
        Objects.equals(this.authors, favoritesResponse.authors) &&
        Objects.equals(this.buddies, favoritesResponse.buddies);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entryId, authors, buddies);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FavoritesResponse {\n");
    
    sb.append("    entryId: ").append(toIndentedString(entryId)).append("\n");
    sb.append("    authors: ").append(toIndentedString(authors)).append("\n");
    sb.append("    buddies: ").append(toIndentedString(buddies)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

