/*
 * Ekşi Sözlük UnPublic API
 * Ekşi sözlük'ün public olmayan apiyı. Bunu kullanmanın size yasal yaptırımları olabilir. Bunu kullanan kişiler bu riski göze almış olarak düşünülür.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: umt.toker@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hasssektor.eksiapi.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * QueryData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-11T23:04:25.106+03:00")
public class QueryData {
  @SerializedName("TopicId")
  private Integer topicId = null;

  @SerializedName("SuggestedTitle")
  private String suggestedTitle = null;

  public QueryData topicId(Integer topicId) {
    this.topicId = topicId;
    return this;
  }

   /**
   * Get topicId
   * @return topicId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTopicId() {
    return topicId;
  }

  public void setTopicId(Integer topicId) {
    this.topicId = topicId;
  }

  public QueryData suggestedTitle(String suggestedTitle) {
    this.suggestedTitle = suggestedTitle;
    return this;
  }

   /**
   * Get suggestedTitle
   * @return suggestedTitle
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSuggestedTitle() {
    return suggestedTitle;
  }

  public void setSuggestedTitle(String suggestedTitle) {
    this.suggestedTitle = suggestedTitle;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryData queryData = (QueryData) o;
    return Objects.equals(this.topicId, queryData.topicId) &&
        Objects.equals(this.suggestedTitle, queryData.suggestedTitle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(topicId, suggestedTitle);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryData {\n");
    
    sb.append("    topicId: ").append(toIndentedString(topicId)).append("\n");
    sb.append("    suggestedTitle: ").append(toIndentedString(suggestedTitle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

