/*
 * Ekşi Sözlük UnPublic API
 * Ekşi sözlük'ün public olmayan apiyı. Bunu kullanmanın size yasal yaptırımları olabilir. Bunu kullanan kişiler bu riski göze almış olarak düşünülür.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: umt.toker@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hasssektor.eksiapi.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Settings
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-11T23:04:25.106+03:00")
public class Settings {
  @SerializedName("IndexPageSize")
  private Integer ındexPageSize = null;

  @SerializedName("TopicPageSize")
  private Integer topicPageSize = null;

  @SerializedName("SkipTrash")
  private Boolean skipTrash = null;

  @SerializedName("MessagingDisabled")
  private Boolean messagingDisabled = null;

  @SerializedName("OnlyBuddiesCanSendMessage")
  private Boolean onlyBuddiesCanSendMessage = null;

  @SerializedName("UseDarkTheme")
  private Boolean useDarkTheme = null;

  @SerializedName("SeylerDisallow")
  private Boolean seylerDisallow = null;

  @SerializedName("ThemeId")
  private Integer themeId = null;

  @SerializedName("ShowFacebookAccount")
  private Boolean showFacebookAccount = null;

  @SerializedName("ShowTwitterAccount")
  private Boolean showTwitterAccount = null;

  @SerializedName("ShowInstagramAccount")
  private Boolean showInstagramAccount = null;

  public Settings ındexPageSize(Integer ındexPageSize) {
    this.ındexPageSize = ındexPageSize;
    return this;
  }

   /**
   * sayfa basina entry sayisi
   * @return ındexPageSize
  **/
  @ApiModelProperty(example = "null", value = "sayfa basina entry sayisi")
  public Integer getIndexPageSize() {
    return ındexPageSize;
  }

  public void setIndexPageSize(Integer ındexPageSize) {
    this.ındexPageSize = ındexPageSize;
  }

  public Settings topicPageSize(Integer topicPageSize) {
    this.topicPageSize = topicPageSize;
    return this;
  }

   /**
   * sayfa basina baslik sayisi
   * @return topicPageSize
  **/
  @ApiModelProperty(example = "null", value = "sayfa basina baslik sayisi")
  public Integer getTopicPageSize() {
    return topicPageSize;
  }

  public void setTopicPageSize(Integer topicPageSize) {
    this.topicPageSize = topicPageSize;
  }

  public Settings skipTrash(Boolean skipTrash) {
    this.skipTrash = skipTrash;
    return this;
  }

   /**
   * Get skipTrash
   * @return skipTrash
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getSkipTrash() {
    return skipTrash;
  }

  public void setSkipTrash(Boolean skipTrash) {
    this.skipTrash = skipTrash;
  }

  public Settings messagingDisabled(Boolean messagingDisabled) {
    this.messagingDisabled = messagingDisabled;
    return this;
  }

   /**
   * Get messagingDisabled
   * @return messagingDisabled
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getMessagingDisabled() {
    return messagingDisabled;
  }

  public void setMessagingDisabled(Boolean messagingDisabled) {
    this.messagingDisabled = messagingDisabled;
  }

  public Settings onlyBuddiesCanSendMessage(Boolean onlyBuddiesCanSendMessage) {
    this.onlyBuddiesCanSendMessage = onlyBuddiesCanSendMessage;
    return this;
  }

   /**
   * Get onlyBuddiesCanSendMessage
   * @return onlyBuddiesCanSendMessage
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getOnlyBuddiesCanSendMessage() {
    return onlyBuddiesCanSendMessage;
  }

  public void setOnlyBuddiesCanSendMessage(Boolean onlyBuddiesCanSendMessage) {
    this.onlyBuddiesCanSendMessage = onlyBuddiesCanSendMessage;
  }

  public Settings useDarkTheme(Boolean useDarkTheme) {
    this.useDarkTheme = useDarkTheme;
    return this;
  }

   /**
   * Get useDarkTheme
   * @return useDarkTheme
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getUseDarkTheme() {
    return useDarkTheme;
  }

  public void setUseDarkTheme(Boolean useDarkTheme) {
    this.useDarkTheme = useDarkTheme;
  }

  public Settings seylerDisallow(Boolean seylerDisallow) {
    this.seylerDisallow = seylerDisallow;
    return this;
  }

   /**
   * Get seylerDisallow
   * @return seylerDisallow
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getSeylerDisallow() {
    return seylerDisallow;
  }

  public void setSeylerDisallow(Boolean seylerDisallow) {
    this.seylerDisallow = seylerDisallow;
  }

  public Settings themeId(Integer themeId) {
    this.themeId = themeId;
    return this;
  }

   /**
   * Get themeId
   * @return themeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getThemeId() {
    return themeId;
  }

  public void setThemeId(Integer themeId) {
    this.themeId = themeId;
  }

  public Settings showFacebookAccount(Boolean showFacebookAccount) {
    this.showFacebookAccount = showFacebookAccount;
    return this;
  }

   /**
   * Get showFacebookAccount
   * @return showFacebookAccount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getShowFacebookAccount() {
    return showFacebookAccount;
  }

  public void setShowFacebookAccount(Boolean showFacebookAccount) {
    this.showFacebookAccount = showFacebookAccount;
  }

  public Settings showTwitterAccount(Boolean showTwitterAccount) {
    this.showTwitterAccount = showTwitterAccount;
    return this;
  }

   /**
   * Get showTwitterAccount
   * @return showTwitterAccount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getShowTwitterAccount() {
    return showTwitterAccount;
  }

  public void setShowTwitterAccount(Boolean showTwitterAccount) {
    this.showTwitterAccount = showTwitterAccount;
  }

  public Settings showInstagramAccount(Boolean showInstagramAccount) {
    this.showInstagramAccount = showInstagramAccount;
    return this;
  }

   /**
   * Get showInstagramAccount
   * @return showInstagramAccount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getShowInstagramAccount() {
    return showInstagramAccount;
  }

  public void setShowInstagramAccount(Boolean showInstagramAccount) {
    this.showInstagramAccount = showInstagramAccount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Settings settings = (Settings) o;
    return Objects.equals(this.ındexPageSize, settings.ındexPageSize) &&
        Objects.equals(this.topicPageSize, settings.topicPageSize) &&
        Objects.equals(this.skipTrash, settings.skipTrash) &&
        Objects.equals(this.messagingDisabled, settings.messagingDisabled) &&
        Objects.equals(this.onlyBuddiesCanSendMessage, settings.onlyBuddiesCanSendMessage) &&
        Objects.equals(this.useDarkTheme, settings.useDarkTheme) &&
        Objects.equals(this.seylerDisallow, settings.seylerDisallow) &&
        Objects.equals(this.themeId, settings.themeId) &&
        Objects.equals(this.showFacebookAccount, settings.showFacebookAccount) &&
        Objects.equals(this.showTwitterAccount, settings.showTwitterAccount) &&
        Objects.equals(this.showInstagramAccount, settings.showInstagramAccount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ındexPageSize, topicPageSize, skipTrash, messagingDisabled, onlyBuddiesCanSendMessage, useDarkTheme, seylerDisallow, themeId, showFacebookAccount, showTwitterAccount, showInstagramAccount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Settings {\n");
    
    sb.append("    ındexPageSize: ").append(toIndentedString(ındexPageSize)).append("\n");
    sb.append("    topicPageSize: ").append(toIndentedString(topicPageSize)).append("\n");
    sb.append("    skipTrash: ").append(toIndentedString(skipTrash)).append("\n");
    sb.append("    messagingDisabled: ").append(toIndentedString(messagingDisabled)).append("\n");
    sb.append("    onlyBuddiesCanSendMessage: ").append(toIndentedString(onlyBuddiesCanSendMessage)).append("\n");
    sb.append("    useDarkTheme: ").append(toIndentedString(useDarkTheme)).append("\n");
    sb.append("    seylerDisallow: ").append(toIndentedString(seylerDisallow)).append("\n");
    sb.append("    themeId: ").append(toIndentedString(themeId)).append("\n");
    sb.append("    showFacebookAccount: ").append(toIndentedString(showFacebookAccount)).append("\n");
    sb.append("    showTwitterAccount: ").append(toIndentedString(showTwitterAccount)).append("\n");
    sb.append("    showInstagramAccount: ").append(toIndentedString(showInstagramAccount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

