/*
 * Ekşi Sözlük UnPublic API
 * Ekşi sözlük'ün public olmayan apiyı. Bunu kullanmanın size yasal yaptırımları olabilir. Bunu kullanan kişiler bu riski göze almış olarak düşünülür.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: umt.toker@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hasssektor.eksiapi.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.hasssektor.eksiapi.models.Author;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * SummaryMessage
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-11T23:04:25.106+03:00")
public class SummaryMessage {
  @SerializedName("Id")
  private Integer ıd = null;

  @SerializedName("User")
  private Author user = null;

  @SerializedName("RawNick")
  private String rawNick = null;

  @SerializedName("IsArchive")
  private Boolean ısArchive = null;

  @SerializedName("MaxMessageId")
  private Integer maxMessageId = null;

  @SerializedName("Unread")
  private Boolean unread = null;

  @SerializedName("UnreadCount")
  private Integer unreadCount = null;

  @SerializedName("Count")
  private Integer count = null;

  @SerializedName("LastUpdate")
  private String lastUpdate = null;

  @SerializedName("Summary")
  private String summary = null;

  @SerializedName("LastUpdateFormatted")
  private String lastUpdateFormatted = null;

  @SerializedName("AvatarUrl")
  private String avatarUrl = null;

  public SummaryMessage ıd(Integer ıd) {
    this.ıd = ıd;
    return this;
  }

   /**
   * Get ıd
   * @return ıd
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getId() {
    return ıd;
  }

  public void setId(Integer ıd) {
    this.ıd = ıd;
  }

  public SummaryMessage user(Author user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @ApiModelProperty(example = "null", value = "")
  public Author getUser() {
    return user;
  }

  public void setUser(Author user) {
    this.user = user;
  }

  public SummaryMessage rawNick(String rawNick) {
    this.rawNick = rawNick;
    return this;
  }

   /**
   * Get rawNick
   * @return rawNick
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRawNick() {
    return rawNick;
  }

  public void setRawNick(String rawNick) {
    this.rawNick = rawNick;
  }

  public SummaryMessage ısArchive(Boolean ısArchive) {
    this.ısArchive = ısArchive;
    return this;
  }

   /**
   * Get ısArchive
   * @return ısArchive
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsArchive() {
    return ısArchive;
  }

  public void setIsArchive(Boolean ısArchive) {
    this.ısArchive = ısArchive;
  }

  public SummaryMessage maxMessageId(Integer maxMessageId) {
    this.maxMessageId = maxMessageId;
    return this;
  }

   /**
   * Get maxMessageId
   * @return maxMessageId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getMaxMessageId() {
    return maxMessageId;
  }

  public void setMaxMessageId(Integer maxMessageId) {
    this.maxMessageId = maxMessageId;
  }

  public SummaryMessage unread(Boolean unread) {
    this.unread = unread;
    return this;
  }

   /**
   * Get unread
   * @return unread
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getUnread() {
    return unread;
  }

  public void setUnread(Boolean unread) {
    this.unread = unread;
  }

  public SummaryMessage unreadCount(Integer unreadCount) {
    this.unreadCount = unreadCount;
    return this;
  }

   /**
   * Get unreadCount
   * @return unreadCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getUnreadCount() {
    return unreadCount;
  }

  public void setUnreadCount(Integer unreadCount) {
    this.unreadCount = unreadCount;
  }

  public SummaryMessage count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public SummaryMessage lastUpdate(String lastUpdate) {
    this.lastUpdate = lastUpdate;
    return this;
  }

   /**
   * Get lastUpdate
   * @return lastUpdate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLastUpdate() {
    return lastUpdate;
  }

  public void setLastUpdate(String lastUpdate) {
    this.lastUpdate = lastUpdate;
  }

  public SummaryMessage summary(String summary) {
    this.summary = summary;
    return this;
  }

   /**
   * Get summary
   * @return summary
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSummary() {
    return summary;
  }

  public void setSummary(String summary) {
    this.summary = summary;
  }

  public SummaryMessage lastUpdateFormatted(String lastUpdateFormatted) {
    this.lastUpdateFormatted = lastUpdateFormatted;
    return this;
  }

   /**
   * Get lastUpdateFormatted
   * @return lastUpdateFormatted
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLastUpdateFormatted() {
    return lastUpdateFormatted;
  }

  public void setLastUpdateFormatted(String lastUpdateFormatted) {
    this.lastUpdateFormatted = lastUpdateFormatted;
  }

  public SummaryMessage avatarUrl(String avatarUrl) {
    this.avatarUrl = avatarUrl;
    return this;
  }

   /**
   * Get avatarUrl
   * @return avatarUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAvatarUrl() {
    return avatarUrl;
  }

  public void setAvatarUrl(String avatarUrl) {
    this.avatarUrl = avatarUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SummaryMessage summaryMessage = (SummaryMessage) o;
    return Objects.equals(this.ıd, summaryMessage.ıd) &&
        Objects.equals(this.user, summaryMessage.user) &&
        Objects.equals(this.rawNick, summaryMessage.rawNick) &&
        Objects.equals(this.ısArchive, summaryMessage.ısArchive) &&
        Objects.equals(this.maxMessageId, summaryMessage.maxMessageId) &&
        Objects.equals(this.unread, summaryMessage.unread) &&
        Objects.equals(this.unreadCount, summaryMessage.unreadCount) &&
        Objects.equals(this.count, summaryMessage.count) &&
        Objects.equals(this.lastUpdate, summaryMessage.lastUpdate) &&
        Objects.equals(this.summary, summaryMessage.summary) &&
        Objects.equals(this.lastUpdateFormatted, summaryMessage.lastUpdateFormatted) &&
        Objects.equals(this.avatarUrl, summaryMessage.avatarUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ıd, user, rawNick, ısArchive, maxMessageId, unread, unreadCount, count, lastUpdate, summary, lastUpdateFormatted, avatarUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SummaryMessage {\n");
    
    sb.append("    ıd: ").append(toIndentedString(ıd)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    rawNick: ").append(toIndentedString(rawNick)).append("\n");
    sb.append("    ısArchive: ").append(toIndentedString(ısArchive)).append("\n");
    sb.append("    maxMessageId: ").append(toIndentedString(maxMessageId)).append("\n");
    sb.append("    unread: ").append(toIndentedString(unread)).append("\n");
    sb.append("    unreadCount: ").append(toIndentedString(unreadCount)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    lastUpdate: ").append(toIndentedString(lastUpdate)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    lastUpdateFormatted: ").append(toIndentedString(lastUpdateFormatted)).append("\n");
    sb.append("    avatarUrl: ").append(toIndentedString(avatarUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

