/*
 * Ekşi Sözlük UnPublic API
 * Ekşi sözlük'ün public olmayan apiyı. Bunu kullanmanın size yasal yaptırımları olabilir. Bunu kullanan kişiler bu riski göze almış olarak düşünülür.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: umt.toker@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hasssektor.eksiapi.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.hasssektor.eksiapi.models.QueryData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TopicQueryResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-11T23:04:25.106+03:00")
public class TopicQueryResponse {
  @SerializedName("Type")
  private String type = null;

  @SerializedName("RedirectFrom")
  private String redirectFrom = null;

  @SerializedName("QueryData")
  private QueryData queryData = null;

  public TopicQueryResponse type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public TopicQueryResponse redirectFrom(String redirectFrom) {
    this.redirectFrom = redirectFrom;
    return this;
  }

   /**
   * Get redirectFrom
   * @return redirectFrom
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRedirectFrom() {
    return redirectFrom;
  }

  public void setRedirectFrom(String redirectFrom) {
    this.redirectFrom = redirectFrom;
  }

  public TopicQueryResponse queryData(QueryData queryData) {
    this.queryData = queryData;
    return this;
  }

   /**
   * Get queryData
   * @return queryData
  **/
  @ApiModelProperty(example = "null", value = "")
  public QueryData getQueryData() {
    return queryData;
  }

  public void setQueryData(QueryData queryData) {
    this.queryData = queryData;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TopicQueryResponse topicQueryResponse = (TopicQueryResponse) o;
    return Objects.equals(this.type, topicQueryResponse.type) &&
        Objects.equals(this.redirectFrom, topicQueryResponse.redirectFrom) &&
        Objects.equals(this.queryData, topicQueryResponse.queryData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, redirectFrom, queryData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TopicQueryResponse {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    redirectFrom: ").append(toIndentedString(redirectFrom)).append("\n");
    sb.append("    queryData: ").append(toIndentedString(queryData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

