/*
 * Ekşi Sözlük UnPublic API
 * Ekşi sözlük'ün public olmayan apiyı. Bunu kullanmanın size yasal yaptırımları olabilir. Bunu kullanan kişiler bu riski göze almış olarak düşünülür.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: umt.toker@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hasssektor.eksiapi.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.hasssektor.eksiapi.models.Entry;
import com.hasssektor.eksiapi.models.EntryCounts;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Topic
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-11T23:04:25.106+03:00")
public class Topic {
  @SerializedName("Id")
  private Integer ıd = null;

  @SerializedName("Title")
  private String title = null;

  @SerializedName("PageCount")
  private Integer pageCount = null;

  @SerializedName("PageSize")
  private Integer pageSize = null;

  @SerializedName("PageIndex")
  private Integer pageIndex = null;

  @SerializedName("EntryCounts")
  private EntryCounts entryCounts = null;

  @SerializedName("DraftEntry")
  private Boolean draftEntry = null;

  @SerializedName("IsTracked")
  private Boolean ısTracked = null;

  @SerializedName("IsTrackable")
  private Boolean ısTrackable = null;

  @SerializedName("Slug")
  private String slug = null;

  @SerializedName("Entries")
  private List<Entry> entries = new ArrayList<Entry>();

  public Topic ıd(Integer ıd) {
    this.ıd = ıd;
    return this;
  }

   /**
   * Get ıd
   * @return ıd
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getId() {
    return ıd;
  }

  public void setId(Integer ıd) {
    this.ıd = ıd;
  }

  public Topic title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Topic pageCount(Integer pageCount) {
    this.pageCount = pageCount;
    return this;
  }

   /**
   * Get pageCount
   * @return pageCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getPageCount() {
    return pageCount;
  }

  public void setPageCount(Integer pageCount) {
    this.pageCount = pageCount;
  }

  public Topic pageSize(Integer pageSize) {
    this.pageSize = pageSize;
    return this;
  }

   /**
   * Get pageSize
   * @return pageSize
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getPageSize() {
    return pageSize;
  }

  public void setPageSize(Integer pageSize) {
    this.pageSize = pageSize;
  }

  public Topic pageIndex(Integer pageIndex) {
    this.pageIndex = pageIndex;
    return this;
  }

   /**
   * Get pageIndex
   * @return pageIndex
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getPageIndex() {
    return pageIndex;
  }

  public void setPageIndex(Integer pageIndex) {
    this.pageIndex = pageIndex;
  }

  public Topic entryCounts(EntryCounts entryCounts) {
    this.entryCounts = entryCounts;
    return this;
  }

   /**
   * Get entryCounts
   * @return entryCounts
  **/
  @ApiModelProperty(example = "null", value = "")
  public EntryCounts getEntryCounts() {
    return entryCounts;
  }

  public void setEntryCounts(EntryCounts entryCounts) {
    this.entryCounts = entryCounts;
  }

  public Topic draftEntry(Boolean draftEntry) {
    this.draftEntry = draftEntry;
    return this;
  }

   /**
   * Get draftEntry
   * @return draftEntry
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getDraftEntry() {
    return draftEntry;
  }

  public void setDraftEntry(Boolean draftEntry) {
    this.draftEntry = draftEntry;
  }

  public Topic ısTracked(Boolean ısTracked) {
    this.ısTracked = ısTracked;
    return this;
  }

   /**
   * Get ısTracked
   * @return ısTracked
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsTracked() {
    return ısTracked;
  }

  public void setIsTracked(Boolean ısTracked) {
    this.ısTracked = ısTracked;
  }

  public Topic ısTrackable(Boolean ısTrackable) {
    this.ısTrackable = ısTrackable;
    return this;
  }

   /**
   * Get ısTrackable
   * @return ısTrackable
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsTrackable() {
    return ısTrackable;
  }

  public void setIsTrackable(Boolean ısTrackable) {
    this.ısTrackable = ısTrackable;
  }

  public Topic slug(String slug) {
    this.slug = slug;
    return this;
  }

   /**
   * Get slug
   * @return slug
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSlug() {
    return slug;
  }

  public void setSlug(String slug) {
    this.slug = slug;
  }

  public Topic entries(List<Entry> entries) {
    this.entries = entries;
    return this;
  }

  public Topic addEntriesItem(Entry entriesItem) {
    this.entries.add(entriesItem);
    return this;
  }

   /**
   * Get entries
   * @return entries
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Entry> getEntries() {
    return entries;
  }

  public void setEntries(List<Entry> entries) {
    this.entries = entries;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Topic topic = (Topic) o;
    return Objects.equals(this.ıd, topic.ıd) &&
        Objects.equals(this.title, topic.title) &&
        Objects.equals(this.pageCount, topic.pageCount) &&
        Objects.equals(this.pageSize, topic.pageSize) &&
        Objects.equals(this.pageIndex, topic.pageIndex) &&
        Objects.equals(this.entryCounts, topic.entryCounts) &&
        Objects.equals(this.draftEntry, topic.draftEntry) &&
        Objects.equals(this.ısTracked, topic.ısTracked) &&
        Objects.equals(this.ısTrackable, topic.ısTrackable) &&
        Objects.equals(this.slug, topic.slug) &&
        Objects.equals(this.entries, topic.entries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ıd, title, pageCount, pageSize, pageIndex, entryCounts, draftEntry, ısTracked, ısTrackable, slug, entries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Topic {\n");
    
    sb.append("    ıd: ").append(toIndentedString(ıd)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    pageCount: ").append(toIndentedString(pageCount)).append("\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("    pageIndex: ").append(toIndentedString(pageIndex)).append("\n");
    sb.append("    entryCounts: ").append(toIndentedString(entryCounts)).append("\n");
    sb.append("    draftEntry: ").append(toIndentedString(draftEntry)).append("\n");
    sb.append("    ısTracked: ").append(toIndentedString(ısTracked)).append("\n");
    sb.append("    ısTrackable: ").append(toIndentedString(ısTrackable)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

