/*
 * Ekşi Sözlük UnPublic API
 * Ekşi sözlük'ün public olmayan apiyı. Bunu kullanmanın size yasal yaptırımları olabilir. Bunu kullanan kişiler bu riski göze almış olarak düşünülür.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: umt.toker@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hasssektor.eksiapi.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.hasssektor.eksiapi.models.Karma;
import com.hasssektor.eksiapi.models.UserEntryCounts;
import com.hasssektor.eksiapi.models.UserIdentifier;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * UserInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-11T23:04:25.106+03:00")
public class UserInfo {
  @SerializedName("UserIdentifier")
  private UserIdentifier userIdentifier = null;

  @SerializedName("RemainingInvitation")
  private Integer remainingInvitation = null;

  @SerializedName("TwitterScreenName")
  private String twitterScreenName = null;

  @SerializedName("FacebookProfileUrl")
  private String facebookProfileUrl = null;

  @SerializedName("FacebookScreenName")
  private String facebookScreenName = null;

  @SerializedName("InstagramScreenName")
  private String ınstagramScreenName = null;

  @SerializedName("InstagramProfileUrl")
  private String ınstagramProfileUrl = null;

  @SerializedName("Karma")
  private Karma karma = null;

  @SerializedName("LastEntryDate")
  private String lastEntryDate = null;

  @SerializedName("IsCaylak")
  private Boolean ısCaylak = null;

  @SerializedName("EntryCounts")
  private UserEntryCounts entryCounts = null;

  public UserInfo userIdentifier(UserIdentifier userIdentifier) {
    this.userIdentifier = userIdentifier;
    return this;
  }

   /**
   * Get userIdentifier
   * @return userIdentifier
  **/
  @ApiModelProperty(example = "null", value = "")
  public UserIdentifier getUserIdentifier() {
    return userIdentifier;
  }

  public void setUserIdentifier(UserIdentifier userIdentifier) {
    this.userIdentifier = userIdentifier;
  }

  public UserInfo remainingInvitation(Integer remainingInvitation) {
    this.remainingInvitation = remainingInvitation;
    return this;
  }

   /**
   * Get remainingInvitation
   * @return remainingInvitation
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getRemainingInvitation() {
    return remainingInvitation;
  }

  public void setRemainingInvitation(Integer remainingInvitation) {
    this.remainingInvitation = remainingInvitation;
  }

  public UserInfo twitterScreenName(String twitterScreenName) {
    this.twitterScreenName = twitterScreenName;
    return this;
  }

   /**
   * Get twitterScreenName
   * @return twitterScreenName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTwitterScreenName() {
    return twitterScreenName;
  }

  public void setTwitterScreenName(String twitterScreenName) {
    this.twitterScreenName = twitterScreenName;
  }

  public UserInfo facebookProfileUrl(String facebookProfileUrl) {
    this.facebookProfileUrl = facebookProfileUrl;
    return this;
  }

   /**
   * Get facebookProfileUrl
   * @return facebookProfileUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFacebookProfileUrl() {
    return facebookProfileUrl;
  }

  public void setFacebookProfileUrl(String facebookProfileUrl) {
    this.facebookProfileUrl = facebookProfileUrl;
  }

  public UserInfo facebookScreenName(String facebookScreenName) {
    this.facebookScreenName = facebookScreenName;
    return this;
  }

   /**
   * Get facebookScreenName
   * @return facebookScreenName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFacebookScreenName() {
    return facebookScreenName;
  }

  public void setFacebookScreenName(String facebookScreenName) {
    this.facebookScreenName = facebookScreenName;
  }

  public UserInfo ınstagramScreenName(String ınstagramScreenName) {
    this.ınstagramScreenName = ınstagramScreenName;
    return this;
  }

   /**
   * Get ınstagramScreenName
   * @return ınstagramScreenName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getInstagramScreenName() {
    return ınstagramScreenName;
  }

  public void setInstagramScreenName(String ınstagramScreenName) {
    this.ınstagramScreenName = ınstagramScreenName;
  }

  public UserInfo ınstagramProfileUrl(String ınstagramProfileUrl) {
    this.ınstagramProfileUrl = ınstagramProfileUrl;
    return this;
  }

   /**
   * Get ınstagramProfileUrl
   * @return ınstagramProfileUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getInstagramProfileUrl() {
    return ınstagramProfileUrl;
  }

  public void setInstagramProfileUrl(String ınstagramProfileUrl) {
    this.ınstagramProfileUrl = ınstagramProfileUrl;
  }

  public UserInfo karma(Karma karma) {
    this.karma = karma;
    return this;
  }

   /**
   * Get karma
   * @return karma
  **/
  @ApiModelProperty(example = "null", value = "")
  public Karma getKarma() {
    return karma;
  }

  public void setKarma(Karma karma) {
    this.karma = karma;
  }

  public UserInfo lastEntryDate(String lastEntryDate) {
    this.lastEntryDate = lastEntryDate;
    return this;
  }

   /**
   * Get lastEntryDate
   * @return lastEntryDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLastEntryDate() {
    return lastEntryDate;
  }

  public void setLastEntryDate(String lastEntryDate) {
    this.lastEntryDate = lastEntryDate;
  }

  public UserInfo ısCaylak(Boolean ısCaylak) {
    this.ısCaylak = ısCaylak;
    return this;
  }

   /**
   * Get ısCaylak
   * @return ısCaylak
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsCaylak() {
    return ısCaylak;
  }

  public void setIsCaylak(Boolean ısCaylak) {
    this.ısCaylak = ısCaylak;
  }

  public UserInfo entryCounts(UserEntryCounts entryCounts) {
    this.entryCounts = entryCounts;
    return this;
  }

   /**
   * Get entryCounts
   * @return entryCounts
  **/
  @ApiModelProperty(example = "null", value = "")
  public UserEntryCounts getEntryCounts() {
    return entryCounts;
  }

  public void setEntryCounts(UserEntryCounts entryCounts) {
    this.entryCounts = entryCounts;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserInfo userInfo = (UserInfo) o;
    return Objects.equals(this.userIdentifier, userInfo.userIdentifier) &&
        Objects.equals(this.remainingInvitation, userInfo.remainingInvitation) &&
        Objects.equals(this.twitterScreenName, userInfo.twitterScreenName) &&
        Objects.equals(this.facebookProfileUrl, userInfo.facebookProfileUrl) &&
        Objects.equals(this.facebookScreenName, userInfo.facebookScreenName) &&
        Objects.equals(this.ınstagramScreenName, userInfo.ınstagramScreenName) &&
        Objects.equals(this.ınstagramProfileUrl, userInfo.ınstagramProfileUrl) &&
        Objects.equals(this.karma, userInfo.karma) &&
        Objects.equals(this.lastEntryDate, userInfo.lastEntryDate) &&
        Objects.equals(this.ısCaylak, userInfo.ısCaylak) &&
        Objects.equals(this.entryCounts, userInfo.entryCounts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userIdentifier, remainingInvitation, twitterScreenName, facebookProfileUrl, facebookScreenName, ınstagramScreenName, ınstagramProfileUrl, karma, lastEntryDate, ısCaylak, entryCounts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserInfo {\n");
    
    sb.append("    userIdentifier: ").append(toIndentedString(userIdentifier)).append("\n");
    sb.append("    remainingInvitation: ").append(toIndentedString(remainingInvitation)).append("\n");
    sb.append("    twitterScreenName: ").append(toIndentedString(twitterScreenName)).append("\n");
    sb.append("    facebookProfileUrl: ").append(toIndentedString(facebookProfileUrl)).append("\n");
    sb.append("    facebookScreenName: ").append(toIndentedString(facebookScreenName)).append("\n");
    sb.append("    ınstagramScreenName: ").append(toIndentedString(ınstagramScreenName)).append("\n");
    sb.append("    ınstagramProfileUrl: ").append(toIndentedString(ınstagramProfileUrl)).append("\n");
    sb.append("    karma: ").append(toIndentedString(karma)).append("\n");
    sb.append("    lastEntryDate: ").append(toIndentedString(lastEntryDate)).append("\n");
    sb.append("    ısCaylak: ").append(toIndentedString(ısCaylak)).append("\n");
    sb.append("    entryCounts: ").append(toIndentedString(entryCounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

