/*
 * Ekşi Sözlük UnPublic API
 * Ekşi sözlük'ün public olmayan apiyı. Bunu kullanmanın size yasal yaptırımları olabilir. Bunu kullanan kişiler bu riski göze almış olarak düşünülür.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: umt.toker@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hasssektor.eksiapi.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * UserEntryCounts
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-11T23:04:25.106+03:00")
public class UserEntryCounts {
  @SerializedName("Total")
  private Integer total = null;

  @SerializedName("LastMonth")
  private Integer lastMonth = null;

  @SerializedName("LastWeek")
  private Integer lastWeek = null;

  @SerializedName("Todat")
  private Integer todat = null;

  public UserEntryCounts total(Integer total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }

  public UserEntryCounts lastMonth(Integer lastMonth) {
    this.lastMonth = lastMonth;
    return this;
  }

   /**
   * Get lastMonth
   * @return lastMonth
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getLastMonth() {
    return lastMonth;
  }

  public void setLastMonth(Integer lastMonth) {
    this.lastMonth = lastMonth;
  }

  public UserEntryCounts lastWeek(Integer lastWeek) {
    this.lastWeek = lastWeek;
    return this;
  }

   /**
   * Get lastWeek
   * @return lastWeek
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getLastWeek() {
    return lastWeek;
  }

  public void setLastWeek(Integer lastWeek) {
    this.lastWeek = lastWeek;
  }

  public UserEntryCounts todat(Integer todat) {
    this.todat = todat;
    return this;
  }

   /**
   * Get todat
   * @return todat
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTodat() {
    return todat;
  }

  public void setTodat(Integer todat) {
    this.todat = todat;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserEntryCounts userEntryCounts = (UserEntryCounts) o;
    return Objects.equals(this.total, userEntryCounts.total) &&
        Objects.equals(this.lastMonth, userEntryCounts.lastMonth) &&
        Objects.equals(this.lastWeek, userEntryCounts.lastWeek) &&
        Objects.equals(this.todat, userEntryCounts.todat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, lastMonth, lastWeek, todat);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserEntryCounts {\n");
    
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    lastMonth: ").append(toIndentedString(lastMonth)).append("\n");
    sb.append("    lastWeek: ").append(toIndentedString(lastWeek)).append("\n");
    sb.append("    todat: ").append(toIndentedString(todat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

