/*
 * Ekşi Sözlük UnPublic API
 * Ekşi sözlük'ün public olmayan apiyı. Bunu kullanmanın size yasal yaptırımları olabilir. Bunu kullanan kişiler bu riski göze almış olarak düşünülür.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: umt.toker@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hasssektor.eksiapi.models;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * UserIdentifier
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-11T23:04:25.106+03:00")
public class UserIdentifier {
  @SerializedName("Nick")
  private String nick = null;

  @SerializedName("Id")
  private Integer ıd = null;

  public UserIdentifier nick(String nick) {
    this.nick = nick;
    return this;
  }

   /**
   * Get nick
   * @return nick
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getNick() {
    return nick;
  }

  public void setNick(String nick) {
    this.nick = nick;
  }

  public UserIdentifier ıd(Integer ıd) {
    this.ıd = ıd;
    return this;
  }

   /**
   * Get ıd
   * @return ıd
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getId() {
    return ıd;
  }

  public void setId(Integer ıd) {
    this.ıd = ıd;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserIdentifier userIdentifier = (UserIdentifier) o;
    return Objects.equals(this.nick, userIdentifier.nick) &&
        Objects.equals(this.ıd, userIdentifier.ıd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nick, ıd);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserIdentifier {\n");
    
    sb.append("    nick: ").append(toIndentedString(nick)).append("\n");
    sb.append("    ıd: ").append(toIndentedString(ıd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

