/*
 * Ekşi Sözlük Unofficial API
 * Ekşi sözlük'ün public olmayan apiyı. Bunu kullanmanın size yasal yaptırımları olabilir. Bunu kullanan kişiler bu riski göze almış olarak düşünülür.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: reklam@eksisozluk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse2001Entry;
import io.swagger.client.model.InlineResponse2001TopicId;
import java.io.IOException;

/**
 * InlineResponse2001Entries
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-03T23:19:51.302Z")
public class InlineResponse2001Entries {
  @SerializedName("TopicId")
  private InlineResponse2001TopicId topicId = null;

  @SerializedName("Entry")
  private InlineResponse2001Entry entry = null;

  public InlineResponse2001Entries topicId(InlineResponse2001TopicId topicId) {
    this.topicId = topicId;
    return this;
  }

   /**
   * Get topicId
   * @return topicId
  **/
  @ApiModelProperty(value = "")
  public InlineResponse2001TopicId getTopicId() {
    return topicId;
  }

  public void setTopicId(InlineResponse2001TopicId topicId) {
    this.topicId = topicId;
  }

  public InlineResponse2001Entries entry(InlineResponse2001Entry entry) {
    this.entry = entry;
    return this;
  }

   /**
   * Get entry
   * @return entry
  **/
  @ApiModelProperty(value = "")
  public InlineResponse2001Entry getEntry() {
    return entry;
  }

  public void setEntry(InlineResponse2001Entry entry) {
    this.entry = entry;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001Entries inlineResponse2001Entries = (InlineResponse2001Entries) o;
    return Objects.equals(this.topicId, inlineResponse2001Entries.topicId) &&
        Objects.equals(this.entry, inlineResponse2001Entries.entry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(topicId, entry);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001Entries {\n");
    
    sb.append("    topicId: ").append(toIndentedString(topicId)).append("\n");
    sb.append("    entry: ").append(toIndentedString(entry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

