/*
 * Ekşi Sözlük Unofficial API
 * Ekşi sözlük'ün public olmayan apiyı. Bunu kullanmanın size yasal yaptırımları olabilir. Bunu kullanan kişiler bu riski göze almış olarak düşünülür.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: reklam@eksisozluk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse2001EntryAuthor;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse2003
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-03T23:19:51.302Z")
public class InlineResponse2003 {
  @SerializedName("EntryId")
  private Integer entryId = null;

  @SerializedName("Caylaks")
  private List<InlineResponse2001EntryAuthor> caylaks = null;

  public InlineResponse2003 entryId(Integer entryId) {
    this.entryId = entryId;
    return this;
  }

   /**
   * Get entryId
   * @return entryId
  **/
  @ApiModelProperty(value = "")
  public Integer getEntryId() {
    return entryId;
  }

  public void setEntryId(Integer entryId) {
    this.entryId = entryId;
  }

  public InlineResponse2003 caylaks(List<InlineResponse2001EntryAuthor> caylaks) {
    this.caylaks = caylaks;
    return this;
  }

  public InlineResponse2003 addCaylaksItem(InlineResponse2001EntryAuthor caylaksItem) {
    if (this.caylaks == null) {
      this.caylaks = new ArrayList<InlineResponse2001EntryAuthor>();
    }
    this.caylaks.add(caylaksItem);
    return this;
  }

   /**
   * Get caylaks
   * @return caylaks
  **/
  @ApiModelProperty(value = "")
  public List<InlineResponse2001EntryAuthor> getCaylaks() {
    return caylaks;
  }

  public void setCaylaks(List<InlineResponse2001EntryAuthor> caylaks) {
    this.caylaks = caylaks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2003 inlineResponse2003 = (InlineResponse2003) o;
    return Objects.equals(this.entryId, inlineResponse2003.entryId) &&
        Objects.equals(this.caylaks, inlineResponse2003.caylaks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entryId, caylaks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2003 {\n");
    
    sb.append("    entryId: ").append(toIndentedString(entryId)).append("\n");
    sb.append("    caylaks: ").append(toIndentedString(caylaks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

