/*
 * Ekşi Sözlük Unofficial API
 * Ekşi sözlük'ün public olmayan apiyı. Bunu kullanmanın size yasal yaptırımları olabilir. Bunu kullanan kişiler bu riski göze almış olarak düşünülür.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: reklam@eksisozluk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse2001EntryAuthor;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineResponse2002
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-03T23:19:51.302Z")
public class InlineResponse2002 {
  @SerializedName("EntryId")
  private Integer entryId = null;

  @SerializedName("Authors")
  private List<InlineResponse2001EntryAuthor> authors = null;

  public InlineResponse2002 entryId(Integer entryId) {
    this.entryId = entryId;
    return this;
  }

   /**
   * Get entryId
   * @return entryId
  **/
  @ApiModelProperty(value = "")
  public Integer getEntryId() {
    return entryId;
  }

  public void setEntryId(Integer entryId) {
    this.entryId = entryId;
  }

  public InlineResponse2002 authors(List<InlineResponse2001EntryAuthor> authors) {
    this.authors = authors;
    return this;
  }

  public InlineResponse2002 addAuthorsItem(InlineResponse2001EntryAuthor authorsItem) {
    if (this.authors == null) {
      this.authors = new ArrayList<InlineResponse2001EntryAuthor>();
    }
    this.authors.add(authorsItem);
    return this;
  }

   /**
   * Get authors
   * @return authors
  **/
  @ApiModelProperty(value = "")
  public List<InlineResponse2001EntryAuthor> getAuthors() {
    return authors;
  }

  public void setAuthors(List<InlineResponse2001EntryAuthor> authors) {
    this.authors = authors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002 inlineResponse2002 = (InlineResponse2002) o;
    return Objects.equals(this.entryId, inlineResponse2002.entryId) &&
        Objects.equals(this.authors, inlineResponse2002.authors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entryId, authors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002 {\n");
    
    sb.append("    entryId: ").append(toIndentedString(entryId)).append("\n");
    sb.append("    authors: ").append(toIndentedString(authors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

