/*
 * Ekşi Sözlük Unofficial API
 * Ekşi sözlük'ün public olmayan apiyı. Bunu kullanmanın size yasal yaptırımları olabilir. Bunu kullanan kişiler bu riski göze almış olarak düşünülür.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: reklam@eksisozluk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.InlineResponse200UserInfoKarma;
import io.swagger.client.model.InlineResponse200UserInfoUserIdentifier;
import java.io.IOException;
import org.joda.time.DateTime;

/**
 * UserInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-03T23:19:51.302Z")
public class UserInfo {
  @SerializedName("UserIdentifier")
  private InlineResponse200UserInfoUserIdentifier userIdentifier = null;

  @SerializedName("RemainingInvitation")
  private Integer remainingInvitation = null;

  @SerializedName("TwitterScreenName")
  private String twitterScreenName = null;

  @SerializedName("FacebookProfileUrl")
  private String facebookProfileUrl = null;

  @SerializedName("FacebookScreenName")
  private String facebookScreenName = null;

  @SerializedName("InstagramScreenName")
  private String instagramScreenName = null;

  @SerializedName("InstagramProfileUrl")
  private String instagramProfileUrl = null;

  @SerializedName("Karma")
  private InlineResponse200UserInfoKarma karma = null;

  @SerializedName("LastEntryDate")
  private DateTime lastEntryDate = null;

  @SerializedName("IsCaylak")
  private Boolean isCaylak = null;

  public UserInfo userIdentifier(InlineResponse200UserInfoUserIdentifier userIdentifier) {
    this.userIdentifier = userIdentifier;
    return this;
  }

   /**
   * Get userIdentifier
   * @return userIdentifier
  **/
  @ApiModelProperty(value = "")
  public InlineResponse200UserInfoUserIdentifier getUserIdentifier() {
    return userIdentifier;
  }

  public void setUserIdentifier(InlineResponse200UserInfoUserIdentifier userIdentifier) {
    this.userIdentifier = userIdentifier;
  }

  public UserInfo remainingInvitation(Integer remainingInvitation) {
    this.remainingInvitation = remainingInvitation;
    return this;
  }

   /**
   * Get remainingInvitation
   * @return remainingInvitation
  **/
  @ApiModelProperty(value = "")
  public Integer getRemainingInvitation() {
    return remainingInvitation;
  }

  public void setRemainingInvitation(Integer remainingInvitation) {
    this.remainingInvitation = remainingInvitation;
  }

  public UserInfo twitterScreenName(String twitterScreenName) {
    this.twitterScreenName = twitterScreenName;
    return this;
  }

   /**
   * Get twitterScreenName
   * @return twitterScreenName
  **/
  @ApiModelProperty(value = "")
  public String getTwitterScreenName() {
    return twitterScreenName;
  }

  public void setTwitterScreenName(String twitterScreenName) {
    this.twitterScreenName = twitterScreenName;
  }

  public UserInfo facebookProfileUrl(String facebookProfileUrl) {
    this.facebookProfileUrl = facebookProfileUrl;
    return this;
  }

   /**
   * Get facebookProfileUrl
   * @return facebookProfileUrl
  **/
  @ApiModelProperty(value = "")
  public String getFacebookProfileUrl() {
    return facebookProfileUrl;
  }

  public void setFacebookProfileUrl(String facebookProfileUrl) {
    this.facebookProfileUrl = facebookProfileUrl;
  }

  public UserInfo facebookScreenName(String facebookScreenName) {
    this.facebookScreenName = facebookScreenName;
    return this;
  }

   /**
   * Get facebookScreenName
   * @return facebookScreenName
  **/
  @ApiModelProperty(value = "")
  public String getFacebookScreenName() {
    return facebookScreenName;
  }

  public void setFacebookScreenName(String facebookScreenName) {
    this.facebookScreenName = facebookScreenName;
  }

  public UserInfo instagramScreenName(String instagramScreenName) {
    this.instagramScreenName = instagramScreenName;
    return this;
  }

   /**
   * Get instagramScreenName
   * @return instagramScreenName
  **/
  @ApiModelProperty(value = "")
  public String getInstagramScreenName() {
    return instagramScreenName;
  }

  public void setInstagramScreenName(String instagramScreenName) {
    this.instagramScreenName = instagramScreenName;
  }

  public UserInfo instagramProfileUrl(String instagramProfileUrl) {
    this.instagramProfileUrl = instagramProfileUrl;
    return this;
  }

   /**
   * Get instagramProfileUrl
   * @return instagramProfileUrl
  **/
  @ApiModelProperty(value = "")
  public String getInstagramProfileUrl() {
    return instagramProfileUrl;
  }

  public void setInstagramProfileUrl(String instagramProfileUrl) {
    this.instagramProfileUrl = instagramProfileUrl;
  }

  public UserInfo karma(InlineResponse200UserInfoKarma karma) {
    this.karma = karma;
    return this;
  }

   /**
   * Get karma
   * @return karma
  **/
  @ApiModelProperty(value = "")
  public InlineResponse200UserInfoKarma getKarma() {
    return karma;
  }

  public void setKarma(InlineResponse200UserInfoKarma karma) {
    this.karma = karma;
  }

  public UserInfo lastEntryDate(DateTime lastEntryDate) {
    this.lastEntryDate = lastEntryDate;
    return this;
  }

   /**
   * Get lastEntryDate
   * @return lastEntryDate
  **/
  @ApiModelProperty(value = "")
  public DateTime getLastEntryDate() {
    return lastEntryDate;
  }

  public void setLastEntryDate(DateTime lastEntryDate) {
    this.lastEntryDate = lastEntryDate;
  }

  public UserInfo isCaylak(Boolean isCaylak) {
    this.isCaylak = isCaylak;
    return this;
  }

   /**
   * Get isCaylak
   * @return isCaylak
  **/
  @ApiModelProperty(value = "")
  public Boolean getIsCaylak() {
    return isCaylak;
  }

  public void setIsCaylak(Boolean isCaylak) {
    this.isCaylak = isCaylak;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserInfo userInfo = (UserInfo) o;
    return Objects.equals(this.userIdentifier, userInfo.userIdentifier) &&
        Objects.equals(this.remainingInvitation, userInfo.remainingInvitation) &&
        Objects.equals(this.twitterScreenName, userInfo.twitterScreenName) &&
        Objects.equals(this.facebookProfileUrl, userInfo.facebookProfileUrl) &&
        Objects.equals(this.facebookScreenName, userInfo.facebookScreenName) &&
        Objects.equals(this.instagramScreenName, userInfo.instagramScreenName) &&
        Objects.equals(this.instagramProfileUrl, userInfo.instagramProfileUrl) &&
        Objects.equals(this.karma, userInfo.karma) &&
        Objects.equals(this.lastEntryDate, userInfo.lastEntryDate) &&
        Objects.equals(this.isCaylak, userInfo.isCaylak);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userIdentifier, remainingInvitation, twitterScreenName, facebookProfileUrl, facebookScreenName, instagramScreenName, instagramProfileUrl, karma, lastEntryDate, isCaylak);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserInfo {\n");
    
    sb.append("    userIdentifier: ").append(toIndentedString(userIdentifier)).append("\n");
    sb.append("    remainingInvitation: ").append(toIndentedString(remainingInvitation)).append("\n");
    sb.append("    twitterScreenName: ").append(toIndentedString(twitterScreenName)).append("\n");
    sb.append("    facebookProfileUrl: ").append(toIndentedString(facebookProfileUrl)).append("\n");
    sb.append("    facebookScreenName: ").append(toIndentedString(facebookScreenName)).append("\n");
    sb.append("    instagramScreenName: ").append(toIndentedString(instagramScreenName)).append("\n");
    sb.append("    instagramProfileUrl: ").append(toIndentedString(instagramProfileUrl)).append("\n");
    sb.append("    karma: ").append(toIndentedString(karma)).append("\n");
    sb.append("    lastEntryDate: ").append(toIndentedString(lastEntryDate)).append("\n");
    sb.append("    isCaylak: ").append(toIndentedString(isCaylak)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

