/*
 * Ekşi Sözlük UnPublic API
 * Ekşi sözlük'ün public olmayan apiyı. Bunu kullanmanın size yasal yaptırımları olabilir. Bunu kullanan kişiler bu riski göze almış olarak düşünülür.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: umt.toker@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hasssektor.eksiapi.apis;

import com.hasssektor.eksiapi.ApiException;
import com.hasssektor.eksiapi.models.AutocomplateNickResponse;
import com.hasssektor.eksiapi.models.AutocomplateResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AutocomplateApi
 */
@Ignore
public class AutocomplateApiTest {

    private final AutocomplateApi api = new AutocomplateApi();

    
    /**
     * hersey icin autocomplate
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void completeTest() throws ApiException {
        String term = null;
        AutocomplateResponse response = api.complete(term);

        // TODO: test validations
    }
    
    /**
     * sadece nickler icin autocomplate
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void completeNickTest() throws ApiException {
        String term = null;
        AutocomplateNickResponse response = api.completeNick(term);

        // TODO: test validations
    }
    
}
