/*
 * Ekşi Sözlük UnPublic API
 * Ekşi sözlük'ün public olmayan apiyı. Bunu kullanmanın size yasal yaptırımları olabilir. Bunu kullanan kişiler bu riski göze almış olarak düşünülür.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: umt.toker@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.hasssektor.eksiapi.apis;

import com.hasssektor.eksiapi.ApiException;
import com.hasssektor.eksiapi.models.MessageThread;
import com.hasssektor.eksiapi.models.MessagesResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MessageApi
 */
@Ignore
public class MessageApiTest {

    private final MessageApi api = new MessageApi();

    
    /**
     * mesajlari getirir
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMessagesTest() throws ApiException {
        Integer p = null;
        MessagesResponse response = api.getMessages(p);

        // TODO: test validations
    }
    
    /**
     * Suserla olan mesajlari getirir (Page 0 dan basliyor)
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getThreadTest() throws ApiException {
        String nick = null;
        MessageThread response = api.getThread(nick);

        // TODO: test validations
    }
    
    /**
     * okunmamis dialog sayisini doner
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUnreadedThreadCountTest() throws ApiException {
        Integer response = api.getUnreadedThreadCount();

        // TODO: test validations
    }
    
    /**
     * Mesaji okundu olarak isaretler
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void markAsReadTest() throws ApiException {
        String nick = null;
        api.markAsRead(nick);

        // TODO: test validations
    }
    
    /**
     * Mesaj atar
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendTest() throws ApiException {
        String to = null;
        String message = null;
        Integer threadId = null;
        MessageThread response = api.send(to, message, threadId);

        // TODO: test validations
    }
    
}
