/*
 * Ekşi Sözlük Unofficial API
 * Ekşi sözlük'ün public olmayan apiyı. Bunu kullanmanın size yasal yaptırımları olabilir. Bunu kullanan kişiler bu riski göze almış olarak düşünülür.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: reklam@eksisozluk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse2002;
import io.swagger.client.model.InlineResponse2003;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EntryApi
 */
@Ignore
public class EntryApiTest {

    private final EntryApi api = new EntryApi();

    
    /**
     * Entryi favorileyen caylakları getirir.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void entryEntryIdCaylakfavoritesGetTest() throws ApiException {
        String entryId = null;
        InlineResponse2003 response = api.entryEntryIdCaylakfavoritesGet(entryId);

        // TODO: test validations
    }
    
    /**
     * Entryi favorileyen suserları getirtir.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void entryEntryIdFavoritesGetTest() throws ApiException {
        String entryId = null;
        InlineResponse2002 response = api.entryEntryIdFavoritesGet(entryId);

        // TODO: test validations
    }
    
}
